// <auto-generated />
using System;
using Agendamento.Date;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agendamento.Migrations
{
    [DbContext(typeof(DateContext))]
    [Migration("20240307224252_CreatePacienteCPFinConsulta")]
    partial class CreatePacienteCPFinConsulta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Agendamento.Models.Consulta", b =>
                {
                    b.Property<int>("Protocolo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Protocolo"));

                    b.Property<int?>("CPF1")
                        .HasColumnType("int");

                    b.Property<string>("DataConsulta")
                        .IsRequired()
                        .HasColumnType("nvarchar(48)");

                    b.Property<int?>("EspecialidadeCRM")
                        .HasColumnType("int");

                    b.Property<int?>("MedicoCRM")
                        .HasColumnType("int");

                    b.Property<int?>("PacienteCPF")
                        .HasColumnType("int");

                    b.HasKey("Protocolo");

                    b.HasIndex("CPF1");

                    b.HasIndex("EspecialidadeCRM");

                    b.HasIndex("MedicoCRM");

                    b.HasIndex("PacienteCPF");

                    b.ToTable("ConsultaDB");
                });

            modelBuilder.Entity("Agendamento.Models.Medico", b =>
                {
                    b.Property<int>("CRM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CRM"));

                    b.Property<string>("Especialidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CRM");

                    b.ToTable("MedicoDB");
                });

            modelBuilder.Entity("Agendamento.Models.Paciente", b =>
                {
                    b.Property<int>("CPF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CPF"));

                    b.Property<int?>("EmailId")
                        .HasColumnType("int");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CPF");

                    b.HasIndex("EmailId");

                    b.ToTable("PacienteDB");
                });

            modelBuilder.Entity("Agendamento.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Agendamento.Models.Consulta", b =>
                {
                    b.HasOne("Agendamento.Models.Paciente", "CPF")
                        .WithMany()
                        .HasForeignKey("CPF1");

                    b.HasOne("Agendamento.Models.Medico", "Especialidade")
                        .WithMany()
                        .HasForeignKey("EspecialidadeCRM");

                    b.HasOne("Agendamento.Models.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoCRM");

                    b.HasOne("Agendamento.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteCPF");

                    b.Navigation("CPF");

                    b.Navigation("Especialidade");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Agendamento.Models.Paciente", b =>
                {
                    b.HasOne("Agendamento.Models.User", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId");

                    b.Navigation("Email");
                });
#pragma warning restore 612, 618
        }
    }
}
